# Generated by Django 5.2.15 on 2026-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_color',
            field=models.CharField(blank=True, default='#f5f3ee', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cta_label',
            field=models.CharField(blank=True, default='Fazer inscrição', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='page_color',
            field=models.CharField(blank=True, default='#0d6c73', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='text_color',
            field=models.CharField(blank=True, default='#222222', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(blank=True, default='#0d6c73', max_length=20),
        ),
    ]
