# Generated by Django 5.2.15 on 2026-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_background_color_event_banner_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/', verbose_name='Arquivo do banner'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_logos/', verbose_name='Arquivo da logo'),
        ),
        migrations.AddField(
            model_name='participant',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='background_color',
            field=models.CharField(blank=True, default='#f5f3ee', max_length=20, verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_url',
            field=models.URLField(blank=True, verbose_name='Banner por URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cta_label',
            field=models.CharField(blank=True, default='Fazer inscrição', max_length=60, verbose_name='Texto do botão principal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=180, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo por URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='page_color',
            field=models.CharField(blank=True, default='#0d6c73', max_length=20, verbose_name='Cor principal'),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_active',
            field=models.BooleanField(default=True, verbose_name='Evento público ativo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Descrição curta'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_color',
            field=models.CharField(blank=True, default='#222222', max_length=20, verbose_name='Cor do texto'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='company',
            field=models.CharField(blank=True, max_length=180, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefone / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(blank=True, max_length=180, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(default='confirmado', max_length=30, verbose_name='Status'),
        ),
    ]
