# Generated by Django 5.2.15 on 2026-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_qr_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_mode',
            field=models.CharField(choices=[('contact', 'Salvar contato'), ('checkin', 'Check-in'), ('both', 'Contato + check-in')], default='both', max_length=20, verbose_name='Modo do QR Code'),
        ),
    ]
