# Generated by Django 5.2.15 on 2026-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizerprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerprofile',
            name='role',
        ),
    ]
