# Generated by Django 5.2.15 on 2026-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_organizerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('basic', 'Operação básica')], default='admin', max_length=20),
        ),
    ]
