# Generated by Django 5.2.15 on 2026-07-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organizerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='allowed_events',
            field=models.ManyToManyField(blank=True, related_name='allowed_organizers', to='core.event'),
        ),
    ]
